
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Akhil Scheduled Runs - Aerodynamic Crawler 
on:
 schedule:
   - cron: '0 8,14,19 * * *' #Runs at 08:00, 14:00 and 19:00 every day
   #- cron: '0 0 1 1 *'  #Disables Cron Job 

defaults:
  run:
    working-directory: aerod-crawler
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Crawler
      env:
        ASP_NET_SessionId: ${{ secrets.ASP_NET_SESSIONID }}
        AEROD_USERNAME: ${{secrets.AEROD_USERNAME}}
        AEROD_PASSWORD: ${{secrets.AEROD_PASSWORD}}
        PLANES:  'ALL'
        DAYS:  30
        TARGET_DATE:  'NONE'
        DURATION_HRS:  3
        STARTING_TIME:  '09:00'
        ENDING_TIME: '20:00'
        SEND_EMAIL: 'YES'
        EMAIL_ADDRESS: 'akhildua97@gmail.com '
      run: |
        python main.py 
      
