
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Nikhil Scheduled Runs - Aerodynamic Crawler 
on:
 schedule:
    #- cron: '0 11 * * 1-5' #"At 11:00 on every day-of-week from Monday through Friday"
    - cron: '*/5 * * * *' 

defaults:
  run:
    working-directory: aerod-crawler
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Crawler
      env:
        ASP_NET_SessionId: ${{ secrets.ASP_NET_SESSIONID }}
        AEROD_USERNAME: ${{secrets.AEROD_USERNAME}}
        AEROD_PASSWORD: ${{secrets.AEROD_PASSWORD}}
        PLANES:  '2838Q'
        DAYS:  30
        TARGET_DATE:  'NONE'
        DURATION_HRS:  4
        STARTING_TIME:  '09:00'
        ENDING_TIME: '20:00'
        SEND_EMAIL: 'YES'
        EMAIL_ADDRESS: 'nikhil9dua@gmail.com'
      run: |
        python main.py 
      
