
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Aerodynamic Crawler 
on:
  workflow_dispatch:
    inputs:
        planes:
          description: "Planes to Choose. Enter as 12234,54102 or ALL"
          default: 'ALL'
          required: false
          type: string
        days:
          description: "Lookahead days"
          default: 45
          type: choice
          options:
            - 15
            - 30
            - 45
            - 60
        target_date:
          description: "Target Date (optional, doesn't work)"
          required: false
          default: "NONE"
        duration_hrs:
          description: "Minimum duration to find (hrs)"
          required: true
          default: 2
        starting_time:
          description: "Starting Time (HH:MM) for Slot"
          required: true
          default: '09:00'
        ending_time:
          description: "Ending Time (HH:MM) for Slot"
          required: true
          default: '20:00'

defaults:
  run:
    working-directory: aerod-crawler
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Crawler
      env:
        ASP_NET_SessionId: ${{ secrets.ASP_NET_SESSIONID }}
        AEROD_USERNAME: ${{secrets.AEROD_USERNAME}}
        AEROD_PASSWORD: ${{secrets.AEROD_USERNAME}}
        PLANES:  ${{ inputs.planes }}
        DAYS:  ${{ inputs.days }}
        TARGET_DATE:  ${{ inputs.target_date }}
        DURATION_HRS:  ${{ inputs.duration_hrs }}
        STARTING_TIME:  ${{ inputs.starting_time }}
        ENDING_TIME: ${{ inputs.ending_time }}
      run: |
        python main.py 
      
